# Generated by Django 5.0.4 on 2024-09-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0003_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='fehca_nacimiento',
            new_name='fecha_nacimiento',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
        ),
    ]
